### ISSUE TITLE
Syncing of contacts continues forever (drains accu and kills phone)

### ISSUE THREAD

**Issue by michaelkarrer81** [Odoo-mobile/messaging#9]
If we do enable the sync of contacts after we connect to the server the sync stops successfully after some seconds. But if we check the sync some hours later (Under Settings -> Accounts -> odoo ) the sync process is always running. 

Process acore uses 100% of one CPU and the mobile phone gets very hot.

Tested with three different android mobile phones against openerp (odoo) v7.0.

If i can do anything that would help with testing or debugging i would happily do so!

**Comment by sysadminmatmoz** [comment]
I can confirm the same issue, tried it on different servers and databases so I can exclude a server side problem. Calendar, groups, messages and notes sync well, contact sync jumps in a never ending loop.

**Comment by michaelkarrer81** [comment]
Now tested and confirmed against android 4.1 to 4.4 with different brands: sony xperia z1, samsung galaxy S3 to S5 and htc one - tested with 7.0 and master (8.0)

**Comment by MahdiFarzami** [comment]
I have same problem and contacts Are not fully synchronized  , i test on HTC Desire HD and Samsung Galaxy Note 10 and Note 3 .

**Comment by rolandwells** [comment]
Confirming the same issue on a nexus 5 against openerp Version 7.0-20140709-231246. Started when contact sync was activated.

**Comment by michaelkarrer81** [comment]
Bug is still there - now also tested with an LG G3 :( - Makes this app useless for me - if i can provide any help to fix this please let me know!!!

**Comment by dpr-odoo** [comment]
Hello,
Issue has been fixed with new app. You can download it from PlayStore
https://play.google.com/store/apps/details?id=com.odoo

Regards,
dpr

**Comment by michaelkarrer81** [comment]
Thank you for the new version but this bug is NOT fixed because the new version of the messaging app will NOT sync the partners to the android address book. 

So in my opinion this bug is either "Never Fix" if you dropped the contacts and calendar sync for the android address book and android calendar or it is still open until this functionality is testable.

By the way i did enable the "Sync server Partners" wich seems to do nothing and also there is no longer a sync option for calendar or contacts in the account settings of my android phone for the odoo account.

Thank you for your good work but i would kindly ask you to tell me/us if you still plan to integrate contacts and calendar sync with the native android address-book and calendar - because if not this app is nearly useless for me and and i guess others and i can stop watching this repositories.

**Comment by mohamedhagag** [comment]
No contacts sync in new version !!
